# Generated by Django 4.2.2 on 2024-07-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место", max_length=200, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Укажите время",
                        verbose_name="Время выполнения  привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие",
                        max_length=250,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "sing_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Введите периодичность от 1 до 7",
                        verbose_name="Периодичность в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "completion_time",
                    models.IntegerField(
                        default=120,
                        help_text="Укажите время на исполнение рпривычки, не более 120 секунд",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "sing_publicity",
                    models.BooleanField(
                        default=False, verbose_name="Привычка опубликована"
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
