# Generated by Django 4.2.2 on 2024-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="completion_time",
            field=models.IntegerField(
                default=120,
                help_text="Укажите время на исполнение привычки, не более 120 секунд",
                verbose_name="Время на выполнение привычки в секундах",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="sing_publicity",
            field=models.BooleanField(default=False, verbose_name="Публичная"),
        ),
    ]
